Search.appendIndex(
    [
                {
            "fqsen": "\\Core\\Settings",
            "name": "Settings",
            "summary": "",
            "url": "classes/Core-Settings.html"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003AloadConfig\u0028\u0029",
            "name": "loadConfig",
            "summary": "",
            "url": "classes/Core-Settings.html#method_loadConfig"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024DB",
            "name": "DB",
            "summary": "",
            "url": "classes/Core-Settings.html#property_DB"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024DB_MODE",
            "name": "DB_MODE",
            "summary": "",
            "url": "classes/Core-Settings.html#property_DB_MODE"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024DB_PATH",
            "name": "DB_PATH",
            "summary": "",
            "url": "classes/Core-Settings.html#property_DB_PATH"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024DB_USER",
            "name": "DB_USER",
            "summary": "",
            "url": "classes/Core-Settings.html#property_DB_USER"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024DB_PASS",
            "name": "DB_PASS",
            "summary": "",
            "url": "classes/Core-Settings.html#property_DB_PASS"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024LOG_IP",
            "name": "LOG_IP",
            "summary": "",
            "url": "classes/Core-Settings.html#property_LOG_IP"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024ANTI_DUPE",
            "name": "ANTI_DUPE",
            "summary": "",
            "url": "classes/Core-Settings.html#property_ANTI_DUPE"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024BLACKLIST_DB",
            "name": "BLACKLIST_DB",
            "summary": "",
            "url": "classes/Core-Settings.html#property_BLACKLIST_DB"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024FILTER_MODE",
            "name": "FILTER_MODE",
            "summary": "",
            "url": "classes/Core-Settings.html#property_FILTER_MODE"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024FILES_ROOT",
            "name": "FILES_ROOT",
            "summary": "",
            "url": "classes/Core-Settings.html#property_FILES_ROOT"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024FILES_RETRIES",
            "name": "FILES_RETRIES",
            "summary": "",
            "url": "classes/Core-Settings.html#property_FILES_RETRIES"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024SSL",
            "name": "SSL",
            "summary": "",
            "url": "classes/Core-Settings.html#property_SSL"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024URL",
            "name": "URL",
            "summary": "",
            "url": "classes/Core-Settings.html#property_URL"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024NAME_LENGTH",
            "name": "NAME_LENGTH",
            "summary": "",
            "url": "classes/Core-Settings.html#property_NAME_LENGTH"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024ID_CHARSET",
            "name": "ID_CHARSET",
            "summary": "",
            "url": "classes/Core-Settings.html#property_ID_CHARSET"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024BLOCKED_EXTENSIONS",
            "name": "BLOCKED_EXTENSIONS",
            "summary": "",
            "url": "classes/Core-Settings.html#property_BLOCKED_EXTENSIONS"
        },                {
            "fqsen": "\\Core\\Settings\u003A\u003A\u0024BLOCKED_MIME",
            "name": "BLOCKED_MIME",
            "summary": "",
            "url": "classes/Core-Settings.html#property_BLOCKED_MIME"
        },                {
            "fqsen": "\\Core\\cuteGrills",
            "name": "cuteGrills",
            "summary": "",
            "url": "classes/Core-cuteGrills.html"
        },                {
            "fqsen": "\\Core\\cuteGrills\u003A\u003AshowGrills\u0028\u0029",
            "name": "showGrills",
            "summary": "",
            "url": "classes/Core-cuteGrills.html#method_showGrills"
        },                {
            "fqsen": "\\Core\\cuteGrills\u003A\u003AloadGrills\u0028\u0029",
            "name": "loadGrills",
            "summary": "",
            "url": "classes/Core-cuteGrills.html#method_loadGrills"
        },                {
            "fqsen": "\\Core\\cuteGrills\u003A\u003A\u0024GRILLS",
            "name": "GRILLS",
            "summary": "",
            "url": "classes/Core-cuteGrills.html#property_GRILLS"
        },                {
            "fqsen": "\\Core\\Response",
            "name": "Response",
            "summary": "",
            "url": "classes/Core-Response.html"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Response.html#method___construct"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003Aerror\u0028\u0029",
            "name": "error",
            "summary": "",
            "url": "classes/Core-Response.html#method_error"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003AcsvError\u0028\u0029",
            "name": "csvError",
            "summary": "",
            "url": "classes/Core-Response.html#method_csvError"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003AhtmlError\u0028\u0029",
            "name": "htmlError",
            "summary": "",
            "url": "classes/Core-Response.html#method_htmlError"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003AjsonError\u0028\u0029",
            "name": "jsonError",
            "summary": "",
            "url": "classes/Core-Response.html#method_jsonError"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003AtextError\u0028\u0029",
            "name": "textError",
            "summary": "",
            "url": "classes/Core-Response.html#method_textError"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "",
            "url": "classes/Core-Response.html#method_send"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003AcsvSuccess\u0028\u0029",
            "name": "csvSuccess",
            "summary": "",
            "url": "classes/Core-Response.html#method_csvSuccess"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003AhtmlSuccess\u0028\u0029",
            "name": "htmlSuccess",
            "summary": "",
            "url": "classes/Core-Response.html#method_htmlSuccess"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003AjsonSuccess\u0028\u0029",
            "name": "jsonSuccess",
            "summary": "",
            "url": "classes/Core-Response.html#method_jsonSuccess"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003AtextSuccess\u0028\u0029",
            "name": "textSuccess",
            "summary": "",
            "url": "classes/Core-Response.html#method_textSuccess"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Core-Response.html#property_type"
        },                {
            "fqsen": "\\Core\\Database",
            "name": "Database",
            "summary": "",
            "url": "classes/Core-Database.html"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003AassemblePDO\u0028\u0029",
            "name": "assemblePDO",
            "summary": "",
            "url": "classes/Core-Database.html#method_assemblePDO"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003AdbCheckNameExists\u0028\u0029",
            "name": "dbCheckNameExists",
            "summary": "",
            "url": "classes/Core-Database.html#method_dbCheckNameExists"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003AcheckFileBlacklist\u0028\u0029",
            "name": "checkFileBlacklist",
            "summary": "",
            "url": "classes/Core-Database.html#method_checkFileBlacklist"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003AantiDupe\u0028\u0029",
            "name": "antiDupe",
            "summary": "",
            "url": "classes/Core-Database.html#method_antiDupe"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003AnewIntoDB\u0028\u0029",
            "name": "newIntoDB",
            "summary": "",
            "url": "classes/Core-Database.html#method_newIntoDB"
        },                {
            "fqsen": "\\Upload",
            "name": "Upload",
            "summary": "",
            "url": "classes/Upload.html"
        },                {
            "fqsen": "\\Upload\u003A\u003AreFiles\u0028\u0029",
            "name": "reFiles",
            "summary": "",
            "url": "classes/Upload.html#method_reFiles"
        },                {
            "fqsen": "\\Upload\u003A\u003AdiverseArray\u0028\u0029",
            "name": "diverseArray",
            "summary": "",
            "url": "classes/Upload.html#method_diverseArray"
        },                {
            "fqsen": "\\Upload\u003A\u003AuploadFile\u0028\u0029",
            "name": "uploadFile",
            "summary": "",
            "url": "classes/Upload.html#method_uploadFile"
        },                {
            "fqsen": "\\Upload\u003A\u003AfileInfo\u0028\u0029",
            "name": "fileInfo",
            "summary": "",
            "url": "classes/Upload.html#method_fileInfo"
        },                {
            "fqsen": "\\Upload\u003A\u003AcheckMimeBlacklist\u0028\u0029",
            "name": "checkMimeBlacklist",
            "summary": "",
            "url": "classes/Upload.html#method_checkMimeBlacklist"
        },                {
            "fqsen": "\\Upload\u003A\u003AcheckExtensionBlacklist\u0028\u0029",
            "name": "checkExtensionBlacklist",
            "summary": "",
            "url": "classes/Upload.html#method_checkExtensionBlacklist"
        },                {
            "fqsen": "\\Upload\u003A\u003AgenerateName\u0028\u0029",
            "name": "generateName",
            "summary": "",
            "url": "classes/Upload.html#method_generateName"
        },                {
            "fqsen": "\\Upload\u003A\u003A\u0024FILE_NAME",
            "name": "FILE_NAME",
            "summary": "",
            "url": "classes/Upload.html#property_FILE_NAME"
        },                {
            "fqsen": "\\Upload\u003A\u003A\u0024FILE_EXTENSION",
            "name": "FILE_EXTENSION",
            "summary": "",
            "url": "classes/Upload.html#property_FILE_EXTENSION"
        },                {
            "fqsen": "\\Upload\u003A\u003A\u0024FILE_MIME",
            "name": "FILE_MIME",
            "summary": "",
            "url": "classes/Upload.html#property_FILE_MIME"
        },                {
            "fqsen": "\\Upload\u003A\u003A\u0024SHA1",
            "name": "SHA1",
            "summary": "",
            "url": "classes/Upload.html#property_SHA1"
        },                {
            "fqsen": "\\Upload\u003A\u003A\u0024NEW_NAME",
            "name": "NEW_NAME",
            "summary": "",
            "url": "classes/Upload.html#property_NEW_NAME"
        },                {
            "fqsen": "\\Upload\u003A\u003A\u0024NEW_NAME_FULL",
            "name": "NEW_NAME_FULL",
            "summary": "",
            "url": "classes/Upload.html#property_NEW_NAME_FULL"
        },                {
            "fqsen": "\\Upload\u003A\u003A\u0024IP",
            "name": "IP",
            "summary": "",
            "url": "classes/Upload.html#property_IP"
        },                {
            "fqsen": "\\Upload\u003A\u003A\u0024FILE_SIZE",
            "name": "FILE_SIZE",
            "summary": "",
            "url": "classes/Upload.html#property_FILE_SIZE"
        },                {
            "fqsen": "\\Upload\u003A\u003A\u0024TEMP_FILE",
            "name": "TEMP_FILE",
            "summary": "",
            "url": "classes/Upload.html#property_TEMP_FILE"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Core",
            "name": "Core",
            "summary": "",
            "url": "namespaces/core.html"
        }            ]
);
