<!DOCTYPE html>
<html lang="en">
   <head>
       <meta charset="utf-8">
       <meta name="viewport" content="width=device-width, initial-scale=1">
       <title>Pantsu.cat &middot; {% block title %}Kawaii File Hosting{% endblock %}</title>
       <link rel="icon" href="favicon.ico">
       <link rel="stylesheet" href="pomf.min.css">
   </head>
   <body>
       <div class="container">
           {% block body %}What the fuck are you doing here, baka?{% endblock %}
       </div>
   </body>
</html>
