<nav>
	<ul><li>
		<a href="http://pomf.se/">Pomf</a></li><li>
		<a href="http://tracker.pomf.se">Torrent Tracker</a></li><li>
		<a href="http://blog.pomf.se/">Blog</a></li><li>
		<a href="irc://irc.pomf.se#cute">IRC</a></li><li>
		<a href="https://twitter.com/nekunekus">Twitter</a></li><li>
		<a href="http://pomf.cat">Forum</a></li><li>
		<a href="http://p.pomf.se/">Paste</a></li><li>
		<a href="http://moe.pomf.se">Moe Login</a></li><li>
		<a href="https://github.com/nokonoko/Pomf">Github</a></li><li>
		<a href="tools.html">Tools</a></li>
	</ul>
</nav>
