<nav>
   <ul>
       <li><a href="//pantsu.cat/">Pantsu</a></li>
       <li><a href="//p.pantsu.cat/">Paste</a></li>
       <li><a href="tools.html">Tools</a></li>
       <li><a href="//github.com/pantsucat/pomf">Github</a></li>
       <li><a href="other.html">Other</a></li>
       <li><a href="//transparency.pantsu.cat">Transparency</a></li>
       <li><a href="ca.html">Catalan</a></li>
	</ul>
</nav>
