{% extends "layout.swig" %}

{% block title %}Other Services{% endblock %}
{% block body %}
<div class="jumbotron">
	<h1>Other Services</h1>
</div>
<ul>
	<li><a href="//git.pantsu.cat">Git</a></li>
	<li><a href="firefox/">Firefox /g/uide</a></li>
	<li><a href="http://mg7aqol36qpx7oij.onion/">Hidden Service</a>
	<li><a href="//no.pantsu.cat">JS Free version</a>
</ul>
{% include "nav.swig" %}
{% endblock %}
