{% extends "layout.swig" %}

{% block title %}Tools{% endblock %}
{% block body %}
<div class="jumbotron">
<h1>Pomf Tools</h1>
{% include "nav.swig" %}
</div>
<section><h1>Pomfit</h1><dl>
	<dt>Download</dt>
		<dd>https://github.com/pantsucat/pomfit</dd>
	<dt>Contact</dt>
		<dd>https://twitter.com/Senketsu_Dev</dd>
</dl></section>
<section><h1>Bash Pomf Uploader</h1><dl>
	<dt>Download</dt>
		<dd>https://gist.github.com/pantsucat/b46320a4103afda4e0ff</dd>
	<dt>Contact</dt>
		<dd>https://twitter.com/AnonymousLink</dd>
</dl></section>
<section><h1>Simple Bash Pomf Uploader</h1><dl>
	<dt>Download</dt>
		<dd>https://gist.github.com/pantsucat/da46d56e22063704604a</dd>
	<dt>Contact</dt>
		<dd>https://twitter.com/dev_console</dd>
</dl></section>
<section><h1>limf</h1><dl>
    <dt>Download</dt>
        <dd><a href="https://github.com/lich/limf">https://github.com/lich/limf</a></dd>
    <dt>Contact</dt>
        <dd><a href="http://lich.github.io/">http://lich.github.io//</a></dd>
</dl></section>
<section><h1>1339secure</h1><dl>
    <dt>Download</dt>
        <dd><a href="https://github.com/pantsucat/1339secure">https://github.com/pantsucat/1339secure</a></dd>
    <dt>Contact</dt>
        <dd><a href="mailto:adriankoshcha@teknik.io">adriankoshcha@teknik.io</a></dd>
</dl></section>
<section><h1>Gyazo Client (Puush like client)</h1><dl>
	<dt>Download</dt>
		<dd>https://github.com/pantsucat/gyazowin</dd>
	<dt>Contact</dt>
		<dd>https://twitter.com/4vailable</dd>
</dl></section>
<section><h1>Python Pomf Uploader</h1><dl>
	<dt>Download</dt>
		<dd>https://github.com/pantsucat/POMF</dd>
	<dt>Contact</dt>
		<dd>https://twitter.com/FuzzyPomf</dd>
</dl></section>
<section><h1>Sharex</h1><dl>
	<dt>Download</dt>
		<dd>https://code.google.com/p/sharex/</dd>
	<dt>Settings</dt>
		<dd>https://p.pantsu.cat/view/raw/977674be</dd>
</dl></section>
<section><h1>Scotty</h1><dl>
	<dt>Download</dt>
		<dd>https://github.com/pantsucat/Scotty</dd>
	<dt>Contact</dt>
		<dd>https://twitter.com/mavanmanenDev</dd>
</dl></section>
<section class="ded"><h1>Bash Screenshot Uploader</h1><dl>
	<dt>Download</dt>
		<dd>https://gist.github.com/aki--aki/6258422</dd>
	<dt>Contact</dt>
		<dd>https://twitter.com/__akiaki</dd>
</dl></section>

<section class="ded"><h1>Pomf.se Windows Client <span class="old">Dead</span></h1><dl>
	<dt>Download</dt>
		<dd>http://mavanmanen.nl/index.php?page=projects</dd>
	<dt>Contact</dt>
		<dd>https://twitter.com/mavanmanenDev</dd>
</dl></section>
<section class="ded"><h1>ScrotUP <span class="old">Dead</span></h1><dl>
	<dt>Download</dt>
		<dd>https://github.com/mavanmanen/ScrotUP</dd>
	<dt>Contact</dt>
		<dd>https://twitter.com/mavanmanenDev</dd>
</dl></section>
<section class="ded"><h1>Perl Pomf Uploaer <span class="old">Dead</span></h1><dl>
	<dt>Download</dt>
		<dd>http://p.pomf.se/624</dd>
	<dt>Contact</dt>
		<dd>Kori</dd>
</dl></section>
{% endblock %}
