{% extends "layout.swig" %}

{% block title %}Tools{% endblock %}
{% block body %}
<div class="jumbotron">
<h1>Pomf Tools</h1>
{% include "nav.swig" %}
</div>
<section><h1>Pomfit</h1><dl>
	<dt>Download</dt>
    <dd><a href="https://github.com/pantsucat/pomfit">https://github.com/pantsucat/pomfit</a></dd>
	<dt>Contact</dt>
		<dd><a href="https://twitter.com/Senketsu_Dev">https://twitter.com/Senketsu_Dev</a></dd>
</dl></section>
<section><h1>Bash Pomf Uploader</h1><dl>
	<dt>Download</dt>
		<dd><a href="https://gist.github.com/pantsucat/b46320a4103afda4e0ff">https://gist.github.com/pantsucat/b46320a4103afda4e0ff</a></dd>
	<dt>Contact</dt>
		<dd><a href="https://twitter.com/AnonymousLink">https://twitter.com/AnonymousLink</a></dd>
</dl></section>
<section><h1>Simple Bash Pomf Uploader</h1><dl>
	<dt>Download</dt>
		<dd><a href="https://gist.github.com/pantsucat/da46d56e22063704604a">https://gist.github.com/pantsucat/da46d56e22063704604a</a></dd>
	<dt>Contact</dt>
		<dd><a href="https://twitter.com/dev_console">https://twitter.com/dev_console</a></dd>
</dl></section>
<section><h1>limf</h1><dl>
    <dt>Download</dt>
        <dd><a href="https://github.com/lich/limf">https://github.com/lich/limf</a></dd>
    <dt>Contact</dt>
        <dd><a href="http://lich.github.io/">http://lich.github.io//</a></dd>
</dl></section>
<section><h1>1339secure</h1><dl>
    <dt>Download</dt>
        <dd><a href="https://github.com/pantsucat/1339secure">https://github.com/pantsucat/1339secure</a></dd>
    <dt>Contact</dt>
        <dd><a href="mailto:adriankoshcha@teknik.io">adriankoshcha@teknik.io</a></dd>
</dl></section>
<section><h1>Python Pomf Uploader</h1><dl>
	<dt>Download</dt>
		<dd><a href="https://github.com/pantsucat/POMF">https://github.com/pantsucat/POMF</a></dd>
	<dt>Contact</dt>
		<dd><a href="https://twitter.com/FuzzyPomf">https://twitter.com/FuzzyPomf</a></dd>
</dl></section>
<section><h1>Sharex</h1><dl>
	<dt>Download</dt>
		<dd><a href="https://code.google.com/p/sharex/">https://code.google.com/p/sharex/</a></dd>
	<dt>Settings</dt>
		<dd><a href="https://p.pantsu.cat/view/raw/b79ea507">https://p.pantsu.cat/view/raw/b79ea507</a></dd>
</dl></section>
<section><h1>Scotty</h1><dl>
	<dt>Download</dt>
		<dd><a href="https://github.com/pantsucat/Scotty">https://github.com/pantsucat/Scotty</a></dd>
	<dt>Contact</dt>
		<dd><a href="https://twitter.com/mavanmanenDev">https://twitter.com/mavanmanenDev</a></dd>
</dl></section>
<section class="ded"><h1>Gyazo Client (Puush like client)</h1><dl>
	<dt>Download</dt>
		<dd><a href="https://github.com/pantsucat/gyazowin">https://github.com/pantsucat/gyazowin</a></dd>
	<dt>Contact</dt>
		<dd><a href="https://twitter.com/4vailable">https://twitter.com/4vailable</a></dd>
</dl></section>
<section class="ded"><h1>Bash Screenshot Uploader</h1><dl>
	<dt>Download</dt>
		<dd><a href="https://gist.github.com/aki--aki/6258422">https://gist.github.com/aki--aki/6258422</a></dd>
	<dt>Contact</dt>
		<dd><a href="https://twitter.com/__akiaki">https://twitter.com/__akiaki</a></dd>
</dl></section>
<section class="ded"><h1>Pomf.se Windows Client <span class="old">Dead</span></h1><dl>
	<dt>Download</dt>
		<dd><a href="http://mavanmanen.nl/index.php?page=projects">http://mavanmanen.nl/index.php?page=projects</a></dd>
	<dt>Contact</dt>
		<dd><a href="https://twitter.com/mavanmanenDev">https://twitter.com/mavanmanenDev</a></dd>
</dl></section>
<section class="ded"><h1>ScrotUP <span class="old">Dead</span></h1><dl>
	<dt>Download</dt>
		<dd><a href="https://github.com/mavanmanen/ScrotUP">https://github.com/mavanmanen/ScrotUP</a></dd>
	<dt>Contact</dt>
		<dd><a href="https://twitter.com/mavanmanenDev">https://twitter.com/mavanmanenDev</a></dd>
</dl></section>
<section class="ded"><h1>Perl Pomf Uploaer <span class="old">Dead</span></h1><dl>
	<dt>Download</dt>
		<dd><a href="http://p.pomf.se/624">http://p.pomf.se/624</a></dd>
	<dt>Contact</dt>
		<dd>Kori</dd>
</dl></section>

{% endblock %}
