{% extends "layout.swig" %}

{% block title %}Tools{% endblock %}
{% block body %}
<div class="jumbotron">
<h1>Pomf Tools</h1>
</div>
<section>
	<h2>pomfload</h2>
	<dl>
		<dt>Download</dt>
		<dd><a href="https://github.com/ewhal/pomfload">https://github.com/ewhal/pomfload</a></dd>
		<dt>Contact</dt>
		<dd><a href="https://twitter.com/AnonymousLink">https://twitter.com/AnonymousLink</a></dd>
	</dl>
</section>
<section>
	<h2>limf</h2>
	<dl>
		<dt>Download</dt>
		<dd><a href="https://github.com/lich/limf">https://github.com/lich/limf</a></dd>
		<dt>Contact</dt>
		<dd><a href="http://lich.github.io/">http://lich.github.io/</a></dd>
	</dl>
</section>
<section>
	<h2>1339secure</h2>
	<dl>
		<dt>Download</dt>
		<dd><a href="https://github.com/AdrianKoshka/1339secure">https://github.com/AdrianKoshka/1339secure</a></dd>
		<dt>Contact</dt>
		<dd><a href="mailto:adriankoshcha@teknik.io">adriankoshcha@teknik.io</a></dd>
	</dl>
</section>
<section>
	<h2>ShareX</h2>
	<dl>
		<dt>Download</dt>
		<dd><a href="https://github.com/ShareX/ShareX/">https://github.com/ShareX/ShareX/</a></dd>
		<dt>Settings</dt>
		<dd><a href="https://p.pantsu.cat/view/raw/8c36da7e">https://p.pantsu.cat/view/raw/8c36da7e</a></dd>
	</dl>
</section>
<section>
	<h2>Gyazowin</h2>
	<dl>
		<dt>Download</dt>
		<dd><a href="https://git.pantsu.cat/pantsu/gyazowin">https://git.pantsu.cat/pantsu/gyazowin</a></dd>
		<dt>Contact</dt>
		<dd><a href="https://twitter.com/4vail">https://twitter.com/4vail</a></dd>
	</dl>
</section>
{% include "nav.swig" %}
{% endblock %}
